# Use postgres/example user/password credentials

services:
  keycloak:
    container_name: baeldung-keycloak.openid-provider
    image: quay.io/keycloak/keycloak:latest
    command:
      - start
      - --import-realm
      - --hostname=localhost
      - --hostname-strict=false
    ports:
      - "9090:9090"
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak/:/opt/keycloak/data/import/
    secrets:
      - postgres_user
      - postgres_password
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: change_me
      KC_HTTP_PORT: 9090
#      KC_HOSTNAME_URL: http://localhost:9090
#      KC_HOSTNAME_ADMIN_URL: http://localhost:9090
#      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_HTTP_RELATIVE_PATH: /
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      # --- Newconfig DB Postgres ---
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_started
    healthcheck:
      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth/health/live' ]
      interval: 5s
      timeout: 5s
      retries: 20

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    secrets:
      - postgres_user
      - postgres_password
    environment:

      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: keycloak   # <-- Create keycloak database at startup
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql   # add volume to persist => changed to comply with postgresql 18+
      #environment:
      #POSTGRES_USER: ${POSTGRES_USER}
      #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_started

volumes:
  keycloak-data:
  postgres-data:

secrets:
  postgres_user:
    file: ./postgres_user.txt
  postgres_password:
    file: ./postgres_password.txt