spring.application.name=lol-demo-server
#keycloak security is active by default
spring.profiles.active=keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/lol-demo-server-realm
spring.security.oauth2.resourceserver.jwt.jws-algorithms=RS256
server.port=8080
app.jwt.secret=${JWT_SECRET}
#24h in ms
app.jwt.expiration= 86400000
#riot.api_key=${RIOT_API_KEY}
riot.data-dragon-base-url=https://ddragon.leagueoflegends.com/cdn/
riot.data-splash-base-url=https://ddragon.leagueoflegends.com/cdn/img/champion/splash/
riot.api-default-version=16.18.1
riot.api-default-language=en_US